name: Lint check

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run lint check
        run: tox -elint-incr
             black --check -diff /home/runner/work/qiskit-terra/qiskit-terra/qiskit/circuit/library/data_preparation/state_preparation.py
             black --check -diff /home/runner/work/qiskit-terra/qiskit-terra/test/python/circuit/test_uniform_superposition_gate.py
